import 'package:flutter/services.dart';

List<String> genres = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Ecchi",
  "Fantasy",
  "Horror",
  "Mecha",
  "Music",
  "Mystery",
  "Psychological",
  "Romance",
  "Sci-Fi",
  "Slice Of Life",
  "Sports",
  "Supernatural",
  "Thriller",
  "Anti-Hero",
  "Female Protagonist",
  "Male Protagonist",
  "Aliens",
  "Artificial Intelligence",
  "Cosplay",
  "Demons",
  "Detective",
  "Dragons",
  "Elf",
  "Ghost",
  "Goblin",
  "Gods",
  "Ninja",
  "Pirates",
  "Robots",
  "Samurai",
  "Vampire",
  "Vikings",
  "Werewolf",
  "Witch",
  "Zombie",
  "Shoujo",
  "Shounen",
  "Historical",
  "Time Skip",
  "Afterlife",
  "Alternate Universe",
  "Augmented Reality",
  "Post-Apocalyptic",
  "Space",
  "Urban Fantasy",
  "Virtual World",
  "Guns",
  "Martial Arts",
  "Swordplay",
  "Acting",
  "Calligraphy",
  "Classic Literature",
  "Drawing",
  "Fashion",
  "Food",
  "Photography",
  "Rakugo",
  "Writing",
  "Band",
  "Dancing",
  "Musical",
  "Parody",
  "Satire",
  "Slapstick",
  "Surreal Comedy",
  "Bullying",
  "Revenge",
  "Body Swapping",
  "Cultivation",
  "Fairy Tale",
  "Henshin",
  "Isekai",
  "Kaiju",
  "Magic",
  "Mythology",
  "Superhero",
];

Future setDefaultOrientation() async {
  await SystemChrome.setPreferredOrientations(
      [DeviceOrientation.portraitDown, DeviceOrientation.portraitUp]);
}

Future setLandscapeOrientation() async {
  await SystemChrome.setPreferredOrientations(
      [DeviceOrientation.landscapeLeft, DeviceOrientation.landscapeRight]);
}
